### ISSUE TITLE
Necessary changes 

### ISSUE THREAD

**Issue by libgin** [AnastasiaChernyshenko/movies-search#1]
1) Should be removed from the project:
- .xcworkspace
- Podfile.lock
- Bundle Pods
2) let requestWithKey = requestString+"api_key=8bacc480e8a0b8b63aec4d7df24bd9e9"  - key should be on top of file or create a new file where to store all constants 
3) Don't use a massive storyboard, one storyboard one viewcontroller
4) Сhange the structure of the project by logical types, the view should be with other views in one folder

**Comment by AnastasiaChernyshenko** [comment]
fixed
